# Generated by Django 2.2.10 on 2020-02-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P', models.IntegerField()),
                ('R', models.IntegerField()),
                ('T', models.IntegerField()),
                ('b1', models.FloatField()),
                ('b2', models.FloatField()),
                ('Sp', models.IntegerField()),
                ('N', models.IntegerField()),
            ],
        ),
    ]
