# Generated by Django 2.2.10 on 2020-02-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='T',
        ),
    ]
