# Generated by Django 2.2.10 on 2020-02-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0003_auto_20200229_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='scb_min_alg',
            field=models.CharField(default='SCB', max_length=8),
        ),
    ]
