# Generated by Django 2.2.10 on 2020-03-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0005_auto_20200301_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P', models.IntegerField()),
                ('R', models.IntegerField()),
                ('scb_alg_min', models.CharField(max_length=8)),
            ],
        ),
    ]
