# Generated by Django 2.2.10 on 2020-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mult', '0006_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='N',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='calculation',
            name='Sp',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='calculation',
            name='b1',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='calculation',
            name='b2',
            field=models.FloatField(default=0.1),
        ),
    ]
